[package]
name = "apint"
version = "0.0.0-alpha.3"
authors = ["Robbepop"]
license = "MIT/Apache-2.0"
readme  = "README.md"

keywords   = ["int", "integer", "precision", "arbitrary"]

repository = "https://github.com/robbepop/apint"
documentation = "https://docs.rs/apint"
description = """Arbitrary precision integers library."""
categories = ["data-structures"]

[dependencies]
smallvec = "0.6"
rand = { version = "0.3", optional = true }
serde = { version = "1.0.0", optional = true }

[features]
rand_support = ["rand"]
serde_support = ["serde"]

[badges]
travis-ci = { repository = "Robbepop/apint" }
appveyor = { repository = "Robbepop/apint", branch = "master", service = "github" }
