[package]
name = "apint"
version = "0.0.0-alpha.1"
authors = ["Robbepop"]
license = "MIT/Apache-2.0"
readme  = "README.md"

keywords   = ["int", "integer", "precision", "arbitrary"]

repository = "https://github.com/robbepop/apint"
documentation = "https://docs.rs/apint"
description = """This library provides efficient integers with arbitrary precision for modulo arithmetic."""
categories = ["data-structures"]

[dependencies]
log = "0.3"
