[package]
name = "apint"
version = "0.2.0" # Don't forget to update html_root_url in lib.rs.
authors = ["Robbepop"]
license = "MIT/Apache-2.0"
readme  = "README.md"

keywords   = ["int", "integer", "precision", "arbitrary"]

repository = "https://github.com/robbepop/apint"
documentation = "https://docs.rs/apint"
description = """Arbitrary precision integers library."""
categories = ["data-structures"]

[dependencies]
smallvec = "0.6"
rand = { version = "0.4", optional = true }
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }

[dev-dependencies]
serde_test = "1.0"
itertools = "0.7"

[features]
default = ["rand_support", "serde_support"]
rand_support = ["rand"]
serde_support = ["serde", "serde_derive"]

[badges]
travis-ci = { repository = "Robbepop/apint" }
appveyor = { repository = "Robbepop/apint", branch = "master", service = "github" }
